apiVersion: v1
kind: Pod
metadata:
  name: static-etcd
  labels:
    role: static-etcd
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: etcd
      image: saidameft/etcd:3.3
      imagePullPolicy: IfNotPresent
      command:
      - etcd
      - --advertise-client-urls=http://0.0.0.0:2379
      volumeMounts:
      - mountPath: /var/lib/etcd
        name: etcd-data
  volumes:
  - name: etcd-data
    hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
