apiVersion: v1
kind: Pod
metadata:
  name: static-controller-manager
  labels:
    role: static-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: controller-manager
      image: saidameft/kube-controller-manager:1.17
      imagePullPolicy: IfNotPresent
      command:
      - kube-controller-manager
      - --master=http://localhost:8080
