apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy
  labels:
    role: kube-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      role: kube-proxy
  template:
    metadata:
      labels:
        role: kube-proxy
    spec:
      hostNetwork: true
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: ""
      containers:
        - name: kube-proxy
          image: saidameft/kube-proxy:4.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
          - name: lib-modules
            mountPath: /lib/modules
            readOnly: true
          command:
          - kube-proxy
          - --master=http://localhost:8080
